name: gtest

on:
  - push
  - pull_request
  - release

jobs:
  gtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Figure out version
        id: tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          COMMITS_SINCE_TAG=$(git rev-list ${TAG}..HEAD --count)
          if [ "${COMMITS_SINCE_TAG}" -eq 0 ]; then
            echo "VERSION=${TAG}" >> $GITHUB_ENV
          else
            echo "VERSION="$(git describe --tags --abbrev=8) >> $GITHUB_ENV
          fi
      - name: Cache Conan2 dependencies
        uses: actions/cache@v3
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan2-${{ hashFiles('**/conanfile.py') }}
          restore-keys: |
            ${{ runner.os }}-conan2-
      - name: Install Conan
        run: pip install conan
      - name: Configure Conan Profile
        run: |
          conan profile detect -e
          conan remote add conan-nexus https://nexus.cridland.io/repository/dwd-conan --force
          conan remote login conan-nexus ci --password ${{ secrets.NEXUS_PASSWORD }}
      - name: Conan Deps (Release)
        run: conan install . -s build_type=Release -s compiler.cppstd=gnu23  -b missing --version=${{ env.VERSION }}
      - name: Conan Deps (Debug)
        run: conan install . -s build_type=Debug -s compiler.cppstd=gnu23  -b missing --version=${{ env.VERSION }}
      - name: Conan Deps (RelWithDebInfo)
        run: conan install . -s build_type=RelWithDebInfo -s compiler.cppstd=gnu23  -b missing --version=${{ env.VERSION }}
      - name: Create package (Release)
        run: conan create . -s build_type=Release -s compiler.cppstd=gnu23  -b missing --version=${{ env.VERSION }}
      - name: Create package (Debug)
        run: conan create . -s build_type=Debug -s compiler.cppstd=gnu23  -b missing --version=${{ env.VERSION }}
      - name: Create package (RelWithDebInfo)
        run: conan create . -s build_type=RelWithDebInfo -s compiler.cppstd=gnu23  -b missing --version=${{ env.VERSION }}
      - name: Upload
        run: conan upload -r conan-nexus --confirm 'unbound/*'
